### PR TITLE
Specifying the System variables

### PR DESCRIPTION
**Pull request by hoytpr**
adding select System variables section

### CODE REVIEW

**Review by maxim-belkin — APPROVED** [review]
Looks good to me! Thanks, Peter!

BTW, do you see "Edit" or "Edit..." button?

**Comment by hoytpr** [comment]
The System buttons are New... , Edit... , and Delete. (With the "w' the "i" and the "l" underlined respectively)

**Comment by maxim-belkin** [comment]
I wonder if we should change "Edit" to "Edit..."

**Comment by hoytpr** [comment]
Probably the more accurate the better. I'm attaching a screenshot
environment_variables

**Comment by hoytpr** [comment]
That is an ugly screen shot on my computer. I'm attaching it again as a /jpg file just in case it's unreadable:
environment_variables

**Pull request merged**
