### PR TITLE
05-rmarkdown-example.Rmd: fix instructions for R-markdown files

### PR DESCRIPTION
**Pull request by maxim-belkin**
Improve code block that specifies what lesson developers have to
add to their Rmd-based episodes.

### CODE REVIEW

**Comment by fmichonneau** [comment]
great, thank you for fixing this!

**Comment by maxim-belkin** [comment]
No worries. I will regenerate corresponding `.md` file after I sync the lesson with the styles repo.

**Comment by maxim-belkin** [comment]
François, when I regenerate the `.md` file (with `make site` or `bin/knit_lessons.sh`) 
I get a Markdown file with code blocks that look like this:

``````
```r
some code
```
or

> ```r
> some other code
> ```
``````

So, apparently, `chunk_options.R` is not engaged.
When I add `source("bin/chunk-options.R")` to `bin/generate_md_episodes.R`, the above code changes to:

``````
~~~
some code
~~~
{: .language-r}
or

~~~
some code
~~~
{: .language-r}
``````
meaning that indentation is lost (`> ` characters). Do you have a  fix for that?

**Comment by fmichonneau** [comment]
Sorry for taking so long to get back to you on this!

I'm not sure I can reproduce what you see. If I have this in an Rmd file:

Screenshot from 2020-02-25 12-15-32

then the output would look like this:

Screenshot from 2020-02-25 12-17-12

Note that if the `r` isn't in curly brackets, the content of the chunk isn't evaluated.

PS: I tweaked a little bit the content of the file and committed the regenerated Markdown.

**Comment by maxim-belkin** [comment]
> I'm not sure I can reproduce what you see.

You fixed that in https://github.com/carpentries/lesson-example/commit/d22c677d67ed6f49b9ec94e8e54de5f78a66a440

**Pull request merged**
