### PR TITLE
Add continuous integration powered by Travis CI

### PR DESCRIPTION
**Pull request by rgaiacs**
@gvwilson wrote a rule on `Makefile` to validate the lesson and we should enforce it use.

### CODE REVIEW

**Comment by rgaiacs** [comment]
@jduckles @ChristinaLK Can you enable Travis CI on this repository?

**Comment by ErinBecker** [comment]
Should this be merged? It looks to me like Travis CI is enabled.

**Comment by rgaiacs** [comment]
> Should this be merged? It looks to me like Travis CI is enabled.

I'm not confident enough on the `.travis` file, yet.

**Comment by fmichonneau** [comment]
we are using GitHub Actions for this now.

**Pull request closed without merging**
