### PR TITLE
Update CoC filename (follow-up to carpentries/styles/#280)

### PR DESCRIPTION
**Pull request by katrinleinweber**
- [x] also update https://raw.githubusercontent.com/carpentries/lesson-example/gh-pages/fig/file-mapping.svg

### CODE REVIEW

**Comment by maxim-belkin** [comment]
You _might_ want to merge `styles/gh-pages` first.

**Comment by fmichonneau** [comment]
Hi @katrinleinweber 

Thanks for this but this repository gets updated after releases to the styles repository. The next release (which should happen today) will include the changes to the file name for the code of conduct and other small fixes. As part of the release process, we have a script that generates the pull requests across all our repositories.

In the past, the lesson infrastructure committee has decided that we don't rebase for releases to keep the history of contributions intact.

Closing here, in favor of a future PR later today.

**Comment by fmichonneau** [comment]
oh I see you also included here the changes within the episode. I'll cherry pick these commits, after merging the updated template. Thanks!

**Comment by maxim-belkin** [comment]
Sorry, @katrinleinweber. This is my fault. I thought this is `r-novice-inflammation` because I saw your name.

**Comment by rgaiacs** [comment]
> However, I learned that search-and-replace works even in SVGs :-)

You should be careful when using search-and-replace for SVG because you can end up with part of the text not showing. For example,

```
<svg height="20" width="50" xmlns:xlink="http://www.w3.org/1999/xlink">
  <text x="0" y="20" fill="red">CoC</text>
</svg>
```

will be render as

screenshot from 2018-06-19 21-43-37

but

```
<svg height="20" width="50" xmlns:xlink="http://www.w3.org/1999/xlink">
  <text x="0" y="20" fill="red">Code of Conduct</text>
</svg>
```

will be render as

screenshot from 2018-06-19 21-43-26

On the previous example, the problem is the size of the SVG canvas but  a similar problem can happen when you are clipping part of one element.

**Pull request closed without merging**
